{application,scrivener,
             [{modules,['Elixir.Collectable.Scrivener.Page',
                        'Elixir.Enumerable.Scrivener.Page','Elixir.Scrivener',
                        'Elixir.Scrivener.Config','Elixir.Scrivener.Page',
                        'Elixir.Scrivener.Paginater']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"Pagination for the Elixir ecosystem"},
              {registered,[]},
              {vsn,"2.7.2"}]}.
